import type { ApiServiceMetric, BudgetConfig, ApiRequestLog } from './cost-monitoring.types';

export const MOCK_API_SERVICES: ApiServiceMetric[] = [
  {
    id: 'api-gmaps',
    serviceName: 'Google Maps Geocoding & Distance Matrix',
    provider: 'Google Maps',
    monthlyCost: '$210.40',
    dailyRequestsCount: 14200,
    dailyLimit: 15000,
    percentUsed: 94.6,
    status: 'danger',
    description: 'Reverse geocoding coordinates to street addresses for live tracking HUD.',
  },
  {
    id: 'api-tomtom',
    serviceName: 'TomTom Speed Limit & Map Matching API',
    provider: 'TomTom',
    monthlyCost: '$145.20',
    dailyRequestsCount: 20500,
    dailyLimit: 25000,
    percentUsed: 82.0,
    status: 'warning',
    description: 'Real-time road speed limit verification and overspeed detection engine.',
  },
  {
    id: 'api-wa',
    serviceName: 'WhatsApp Business Messaging API',
    provider: 'WhatsApp',
    monthlyCost: '$38.50',
    dailyRequestsCount: 1250,
    dailyLimit: 5000,
    percentUsed: 25.0,
    status: 'normal',
    description: 'Automated QR invite delivery and critical SOS emergency broadcasts.',
  },
  {
    id: 'api-fcm',
    serviceName: 'Firebase Cloud Messaging (Push Notifications)',
    provider: 'Firebase FCM',
    monthlyCost: '$0.00 (Free Tier)',
    dailyRequestsCount: 142000,
    dailyLimit: 500000,
    percentUsed: 28.4,
    status: 'normal',
    description: 'High-throughput system notifications and speed alert push delivery.',
  },
];

export const MOCK_BUDGET_CONFIG: BudgetConfig = {
  monthlySpendCap: 500.0,
  currentSpend: 394.1,
  warningThresholdPercent: 80,
  criticalThresholdPercent: 95,
  autoLockoutEnabled: false,
};

export const MOCK_API_LOGS: ApiRequestLog[] = [
  {
    id: 'log-001',
    timestamp: '2 secs ago',
    service: 'Google Maps',
    endpoint: '/maps/api/geocode/json?latlng=12.9716,77.5946',
    responseTimeMs: 142,
    costCents: 0.5,
    httpStatus: 200,
    groupName: 'Express Logistics North Fleet',
  },
  {
    id: 'log-002',
    timestamp: '14 secs ago',
    service: 'TomTom',
    endpoint: '/routing/1/calculateRoute/speedLimit?speed=115',
    responseTimeMs: 88,
    costCents: 0.3,
    httpStatus: 200,
    groupName: 'Express Logistics North Fleet',
  },
  {
    id: 'log-003',
    timestamp: '45 secs ago',
    service: 'TomTom',
    endpoint: '/routing/1/calculateRoute/speedLimit?speed=120',
    responseTimeMs: 95,
    costCents: 0.3,
    httpStatus: 429,
    groupName: 'Bangalore Weekend Cycling Club',
  },
  {
    id: 'log-004',
    timestamp: '2 mins ago',
    service: 'WhatsApp',
    endpoint: '/v16.0/messages (template: sos_alert_v2)',
    responseTimeMs: 310,
    costCents: 2.5,
    httpStatus: 200,
    groupName: 'Express Logistics North Fleet',
  },
  {
    id: 'log-005',
    timestamp: '5 mins ago',
    service: 'Firebase FCM',
    endpoint: '/fcm/send (topic: speed_warnings)',
    responseTimeMs: 45,
    costCents: 0.0,
    httpStatus: 200,
  },
];
