import type { GroupAdminSummary, GroupMemberRecord, GroupJoinRequest } from './admin.types';

export const MOCK_ADMIN_GROUPS: GroupAdminSummary[] = [
  {
    id: 'grp-001',
    name: 'Express Logistics North Fleet',
    category: 'Delivery',
    myRole: 'Super Admin',
    totalMembers: 24,
    onlineMembers: 18,
    activeAlerts: 2,
    trackingPolicy: 'Continuous',
    visibilityRule: 'Only Admin',
  },
  {
    id: 'grp-002',
    name: 'Bangalore Weekend Cycling Club',
    category: 'Friends',
    myRole: 'Group Admin',
    totalMembers: 15,
    onlineMembers: 6,
    activeAlerts: 0,
    trackingPolicy: 'Optional',
    visibilityRule: 'Everyone',
  },
];

export const MOCK_GROUP_MEMBERS: GroupMemberRecord[] = [
  {
    id: 'mem-101',
    groupId: 'grp-001',
    name: 'Ramesh Driver (KA-01-EQ-9988)',
    mobile: '+91 98111 11111',
    role: 'Member',
    status: 'active',
    currentSpeed: '64 km/h',
    batteryPercent: 88,
    lastSeen: 'Live Now',
  },
  {
    id: 'mem-102',
    groupId: 'grp-001',
    name: 'Suresh Kumar (KA-04-AB-1234)',
    mobile: '+91 98222 22222',
    role: 'Member',
    status: 'active',
    currentSpeed: '45 km/h',
    batteryPercent: 92,
    lastSeen: 'Live Now',
  },
  {
    id: 'mem-103',
    groupId: 'grp-001',
    name: 'Vikramaditya Sharma (Supervisor)',
    mobile: '+91 98765 43210',
    role: 'Group Admin',
    status: 'active',
    currentSpeed: '0 km/h (Stationary)',
    batteryPercent: 74,
    lastSeen: '2 mins ago',
  },
  {
    id: 'mem-104',
    groupId: 'grp-001',
    name: 'Amitabh Verma (KA-02-XY-5544)',
    mobile: '+91 98333 33333',
    role: 'Member',
    status: 'suspended',
    currentSpeed: '0 km/h',
    batteryPercent: 15,
    lastSeen: 'Yesterday',
  },
  {
    id: 'mem-105',
    groupId: 'grp-002',
    name: 'Rohan Mehta (Club Captain)',
    mobile: '+91 99000 88776',
    role: 'Group Admin',
    status: 'active',
    currentSpeed: '22 km/h',
    batteryPercent: 85,
    lastSeen: 'Live Now',
  },
  {
    id: 'mem-106',
    groupId: 'grp-002',
    name: 'Priya Verma',
    mobile: '+91 96666 55443',
    role: 'Moderator',
    status: 'active',
    currentSpeed: '18 km/h',
    batteryPercent: 91,
    lastSeen: 'Live Now',
  },
  {
    id: 'mem-107',
    groupId: 'grp-002',
    name: 'Karan Johar',
    mobile: '+91 91234 56789',
    role: 'Member',
    status: 'active',
    currentSpeed: '0 km/h (Resting)',
    batteryPercent: 60,
    lastSeen: '12 mins ago',
  },
];

export const MOCK_JOIN_REQUESTS: GroupJoinRequest[] = [
  {
    id: 'req-201',
    groupId: 'grp-001',
    groupName: 'Express Logistics North Fleet',
    userName: 'Mahesh Driver (New Hire)',
    mobile: '+91 90000 11111',
    requestedAt: '15 mins ago',
    status: 'pending',
  },
  {
    id: 'req-202',
    groupId: 'grp-002',
    groupName: 'Bangalore Weekend Cycling Club',
    userName: 'Shreya Ghoshal',
    mobile: '+91 90000 22222',
    requestedAt: '1 hour ago',
    status: 'pending',
  },
];
