import type { AlertRecord } from './alerts.types';

export const MOCK_ALERTS: AlertRecord[] = [
  {
    id: 'alert-1',
    type: 'speed',
    title: 'High Speed Limit Violation',
    description: 'Vehicle UP-16-T-8854 exceeded the 80 km/h highway speed limit.',
    severity: 'high',
    timeLabel: '10 mins ago',
    isRead: false,
    location: 'Outer Bypass Highway Crossing',
    extraInfo: 'Recorded Speed: 95 km/h. Allowed: 80 km/h.',
  },
  {
    id: 'alert-2',
    type: 'hazard',
    title: 'Flooding & Lane Obstruction',
    description: 'Severe water logging reported inside the Sector 62 underpass detour.',
    severity: 'medium',
    timeLabel: '25 mins ago',
    isRead: false,
    location: 'Sector 62 Subway Crossing',
    extraInfo: 'Detour alternative suggested: Expressway Route.',
  },
  {
    id: 'alert-3',
    type: 'safety',
    title: 'Panic Button Pressed',
    description: 'Vehicle UP-16-V-5541 reported panic button trigger from primary seat 3.',
    severity: 'high',
    timeLabel: '1 hour ago',
    isRead: true,
    location: 'St. Mary School Ground Yard',
    extraInfo: 'Trigger resolved: Driver Ramesh Singh reported false alarm test.',
  },
  {
    id: 'alert-4',
    type: 'group',
    title: 'Group Join Request',
    description: 'Co-driver Vipin Sharma requested to join School Bus Operator Group East.',
    severity: 'low',
    timeLabel: '2 hours ago',
    isRead: false,
    location: 'Noida Sector 12 Hub',
    extraInfo: 'Awaiting Administrator group-owner review.',
  },
  {
    id: 'alert-5',
    type: 'hazard',
    title: 'Minor Traffic Jam Warning',
    description: 'Congestion detected on Service Lane Inner Route due to public rally.',
    severity: 'low',
    timeLabel: '4 hours ago',
    isRead: true,
    location: 'Lane 4 Crossroad Intersection',
    extraInfo: 'Est. delay: 15 mins. Alternate: Expressway.',
  },
];
