import type { TripRecord } from './trips.types';

export const MOCK_TRIPS: TripRecord[] = [
  {
    id: 'trip-1',
    routeLabel: 'Sector 12 School Route to Depot 3',
    driverLabel: 'Ramesh Singh',
    vehicleLabel: 'Bus UP-16-T-1024',
    startTime: '08:00 AM',
    endTime: '08:45 AM',
    date: '2026-07-18',
    distance: 14.5,
    duration: '45 mins',
    avgSpeed: 42.5,
    maxSpeed: 62.0,
    status: 'completed',
  },
  {
    id: 'trip-2',
    routeLabel: 'Central Terminal to Outer Bypass Express',
    driverLabel: 'Amit Kumar',
    vehicleLabel: 'Bus UP-16-T-8854',
    startTime: '09:15 AM',
    endTime: '10:30 AM',
    date: '2026-07-18',
    distance: 28.0,
    duration: '1h 15m',
    avgSpeed: 58.0,
    maxSpeed: 84.0,
    status: 'completed',
  },
  {
    id: 'trip-3',
    routeLabel: 'High School Pick-up Loop B',
    driverLabel: 'Jaspreet Singh',
    vehicleLabel: 'Van UP-16-V-5541',
    startTime: '11:00 AM',
    endTime: '--:--',
    date: '2026-07-18',
    distance: 8.2,
    duration: 'Active 20m',
    avgSpeed: 38.0,
    maxSpeed: 52.0,
    status: 'active',
  },
  {
    id: 'trip-4',
    routeLabel: 'Evening Drop-off Route (Primary Section)',
    driverLabel: 'Ramesh Singh',
    vehicleLabel: 'Bus UP-16-T-1024',
    startTime: '03:30 PM',
    endTime: '04:15 PM',
    date: '2026-07-18',
    distance: 14.5,
    duration: '45 mins',
    avgSpeed: 0,
    maxSpeed: 0,
    status: 'scheduled',
  },
  {
    id: 'trip-5',
    routeLabel: 'Sector 62 Transit to Depot Yard',
    driverLabel: 'Sanjay Dutt',
    vehicleLabel: 'Bus UP-16-T-3211',
    startTime: '07:30 PM',
    endTime: '08:15 PM',
    date: '2026-07-17',
    distance: 11.2,
    duration: '45 mins',
    avgSpeed: 40.0,
    maxSpeed: 55.0,
    status: 'completed',
  },
];
