import type { TrackedMember } from './live-map.types';

export const trackedMembers: TrackedMember[] = [
  {
    id: 'member-aarav',
    name: 'Aarav Sharma',
    initials: 'AS',
    status: 'online',
    speed: 42,
    battery: 78,
    lastSeen: 'Just now',
    distance: '1.2 km away',
    location: 'Sector 62, Noida',
    position: { x: 28, y: 38 },
  },
  {
    id: 'member-meera',
    name: 'Meera Singh',
    initials: 'MS',
    status: 'stale',
    speed: 18,
    battery: 41,
    lastSeen: '8 minutes ago',
    distance: '4.8 km away',
    location: 'NH-48, Gurugram',
    position: { x: 67, y: 26 },
  },
  {
    id: 'member-rohan',
    name: 'Rohan Verma',
    initials: 'RV',
    status: 'offline',
    speed: null,
    battery: 22,
    lastSeen: '32 minutes ago',
    distance: '9.1 km away',
    location: 'Connaught Place, Delhi',
    position: { x: 58, y: 68 },
  },
  {
    id: 'member-kavya',
    name: 'Kavya Patel',
    initials: 'KP',
    status: 'online',
    speed: 35,
    battery: 89,
    lastSeen: '1 minute ago',
    distance: '2.6 km away',
    location: 'DND Flyway, Noida',
    position: { x: 38, y: 76 },
  },
];
