import type { TrackedMember } from './live-map.types';

// Real Dubai coordinates — Downtown, Marina, JBR, DIFC, Business Bay, Palm Jumeirah
export const trackedMembers: TrackedMember[] = [
  {
    id: 'member-aarav',
    name: 'Aarav Sharma',
    initials: 'AS',
    status: 'online',
    speed: 62,
    battery: 78,
    lastSeen: 'Just now',
    distance: '1.2 km away',
    location: 'Burj Khalifa, Downtown Dubai',
    position: { x: 48, y: 52 },
    lat: 25.1972,
    lng: 55.2744,
  },
  {
    id: 'member-meera',
    name: 'Meera Singh',
    initials: 'MS',
    status: 'stale',
    speed: 34,
    battery: 41,
    lastSeen: '8 minutes ago',
    distance: '4.8 km away',
    location: 'Dubai Marina Walk',
    position: { x: 22, y: 68 },
    lat: 25.0805,
    lng: 55.1403,
  },
  {
    id: 'member-rohan',
    name: 'Rohan Verma',
    initials: 'RV',
    status: 'offline',
    speed: null,
    battery: 22,
    lastSeen: '32 minutes ago',
    distance: '6.1 km away',
    location: 'DIFC Gate Village',
    position: { x: 66, y: 34 },
    lat: 25.2138,
    lng: 55.2806,
  },
  {
    id: 'member-kavya',
    name: 'Kavya Patel',
    initials: 'KP',
    status: 'online',
    speed: 88,
    battery: 89,
    lastSeen: '1 minute ago',
    distance: '2.6 km away',
    location: 'JBR — Jumeirah Beach',
    position: { x: 14, y: 72 },
    lat: 25.0774,
    lng: 55.1332,
  },
  {
    id: 'member-user',
    name: 'You (Live)',
    initials: 'YO',
    status: 'online',
    speed: 45,
    battery: 95,
    lastSeen: 'Live',
    distance: '0 km',
    location: 'Business Bay, Dubai',
    position: { x: 50, y: 50 },
    lat: 25.1868,
    lng: 55.2765,
  },
];
