import type {
  OwnerPlatformStats,
  PendingGroupApproval,
  PlatformUser,
  PlatformAlert,
} from './owner.types';

export const MOCK_PLATFORM_STATS: OwnerPlatformStats = {
  totalUsers: 1428,
  usersTrendPercent: 14.2,
  activeGroups: 86,
  groupsTrendPercent: 8.5,
  pendingApprovals: 3,
  activeTrackingSessions: 312,
  estimatedMonthlyRevenue: '$4,850.00',
  revenueTrendPercent: 18.4,
  systemAlertsCount: 5,
};

export const MOCK_PENDING_APPROVALS: PendingGroupApproval[] = [
  {
    id: 'appr-101',
    groupName: 'Express Logistics North Fleet',
    category: 'Delivery',
    requestedBy: 'Vikramaditya Sharma',
    mobile: '+91 98765 43210',
    requestedAt: '10 mins ago',
    privacy: 'Private',
    initialMembersCount: 24,
    status: 'pending',
    notes: 'Requires continuous tracking & commercial fleet speed monitoring.',
  },
  {
    id: 'appr-102',
    groupName: 'St. Xavier School Bus Route 12',
    category: 'School',
    requestedBy: 'Anjali Deshmukh',
    mobile: '+91 98111 22334',
    requestedAt: '45 mins ago',
    privacy: 'Private',
    initialMembersCount: 42,
    status: 'pending',
    notes: 'School transport coordination with parents & driver tracking.',
  },
  {
    id: 'appr-103',
    groupName: 'Bangalore Weekend Cycling Club',
    category: 'Friends',
    requestedBy: 'Rohan Mehta',
    mobile: '+91 99000 88776',
    requestedAt: '2 hours ago',
    privacy: 'Public',
    initialMembersCount: 15,
    status: 'pending',
    notes: 'Public discovery group for weekend riders.',
  },
];

export const MOCK_PLATFORM_USERS: PlatformUser[] = [
  {
    id: 'usr-001',
    name: 'Kiaan Priya (You)',
    mobile: '+91 98989 89898',
    email: 'kiaan.priya@transport.app',
    role: 'Group Owner',
    status: 'active',
    joinedAt: '12 Jan 2026',
    groupsCount: 12,
    lastSeen: 'Online Now',
  },
  {
    id: 'usr-002',
    name: 'Vikramaditya Sharma',
    mobile: '+91 98765 43210',
    email: 'vikram@expressfleet.in',
    role: 'Super Admin',
    status: 'active',
    joinedAt: '18 Feb 2026',
    groupsCount: 5,
    lastSeen: '5 mins ago',
  },
  {
    id: 'usr-003',
    name: 'Anjali Deshmukh',
    mobile: '+91 98111 22334',
    email: 'anjali@stxavier.edu',
    role: 'Group Admin',
    status: 'active',
    joinedAt: '03 Mar 2026',
    groupsCount: 3,
    lastSeen: '1 hour ago',
  },
  {
    id: 'usr-004',
    name: 'Rajesh Kumar Singh',
    mobile: '+91 97777 66554',
    role: 'Moderator',
    status: 'active',
    joinedAt: '22 Apr 2026',
    groupsCount: 2,
    lastSeen: 'Yesterday',
  },
  {
    id: 'usr-005',
    name: 'Priya Verma',
    mobile: '+91 96666 55443',
    email: 'priya.v@gmail.com',
    role: 'Member',
    status: 'active',
    joinedAt: '14 May 2026',
    groupsCount: 4,
    lastSeen: '2 hours ago',
  },
  {
    id: 'usr-006',
    name: 'Deepak Chopra',
    mobile: '+91 95555 44332',
    role: 'Member',
    status: 'suspended',
    joinedAt: '01 Jun 2026',
    groupsCount: 1,
    lastSeen: '6 days ago',
  },
  {
    id: 'usr-007',
    name: 'Neha Nair',
    mobile: '+91 94444 33221',
    role: 'Group Guest',
    status: 'pending',
    joinedAt: 'Today',
    groupsCount: 0,
    lastSeen: 'Never',
  },
];

export const MOCK_PLATFORM_ALERTS: PlatformAlert[] = [
  {
    id: 'alt-001',
    title: 'Severe Overspeed Violation (>110 km/h)',
    description: 'Vehicle KA-01-EQ-9988 exceeded maximum safe limit on NH-48 Highway stretch.',
    severity: 'danger',
    timestamp: '8 mins ago',
    groupName: 'Express Logistics North Fleet',
    resolved: false,
  },
  {
    id: 'alt-002',
    title: 'TomTom API Daily Quota Warning (82% reached)',
    description: 'Geocoding and Speed Limit calls are approaching the assigned daily free-tier limit.',
    severity: 'warning',
    timestamp: '25 mins ago',
    resolved: false,
  },
  {
    id: 'alt-003',
    title: 'SOS Emergency Trigger Cancelled',
    description: 'Member Rohan Mehta activated SOS and successfully cancelled within the 5-second safety window.',
    severity: 'info',
    timestamp: '1 hour ago',
    groupName: 'Bangalore Weekend Cycling Club',
    resolved: true,
  },
  {
    id: 'alt-004',
    title: 'New Commercial Group Pending Review',
    description: 'Express Logistics requested creation of a 24-member fleet tracking cluster.',
    severity: 'info',
    timestamp: '2 hours ago',
    groupName: 'Express Logistics North Fleet',
    resolved: false,
  },
];
